//! Weave 桌面壳（Tauri 2 + React + TypeScript + Vite）。
//!
//! 依赖方向：UI → IPC → Application(本 crate) → weave-core → Adapter → OS。
//! 本 crate 是 IPC 边界与 Application 层，不承载领域逻辑。
//! 单元测试放在 `tests/`（集成测试目标）——测试可执行文件需要嵌入
//! common-controls manifest 才能在 Windows 上启动（见 build.rs）。

pub mod app_info;
pub mod batch_service;
pub mod commands;
pub mod config;
pub mod data_service;
pub mod document_service;
pub mod duplicates_service;
pub mod files_dto;
pub mod image_batch_service;
pub mod image_service;
pub mod jobs;
pub mod logging;
pub mod m2_commands;
pub mod m3_commands;
pub mod m4_commands;
pub mod ops_dto;
pub mod rename_service;
pub mod state;
pub mod text_dto;
pub mod text_service;
pub mod tools;
pub mod utilities_service;

use tauri::Manager;
use tauri_specta::{Builder, collect_commands};

/// IPC 契约：所有命令集中注册，类型由 tauri-specta 生成到 `ui/src/generated/bindings.ts`。
pub fn ipc_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::ping,
        commands::get_app_info,
        commands::get_app_config,
        commands::set_app_config,
        commands::inspect_file,
        commands::hash_file,
        commands::analyze_directory,
        commands::get_job,
        commands::cancel_job,
        commands::list_tools,
        m2_commands::build_rename_plan,
        m2_commands::build_organizer_plan,
        m2_commands::execute_plan,
        m2_commands::undo_operation,
        m2_commands::get_history,
        m2_commands::get_operation,
        m3_commands::scan_duplicates,
        m3_commands::build_recycle_plan,
        m3_commands::execute_recycle_plan,
        m4_commands::load_text_document,
        m4_commands::format_text,
        m4_commands::transform_text,
        m4_commands::extract_text,
        m4_commands::compare_text,
        m4_commands::build_text_write_plan,
        m4_commands::execute_text_plan,
        data_service::data_open,
        data_service::data_page,
        data_service::data_set_view,
        data_service::data_inspect_profiles,
        data_service::data_preview_transform,
        data_service::data_apply_transform,
        data_service::data_export,
        data_service::data_close,
        image_service::image_open,
        image_service::image_preview,
        image_service::image_execute,
        image_service::image_cancel,
        image_batch_service::image_batch_execute,
        batch_service::batch_preview,
        batch_service::batch_execute,
        batch_service::batch_pause,
        batch_service::batch_resume,
        batch_service::batch_retry_failed,
        batch_service::batch_jobs_list,
        document_service::document_inspect,
        document_service::pdf_merge_preview,
        document_service::pdf_merge_execute,
        document_service::pdf_extract_execute,
        document_service::pdf_rotate_execute,
        document_service::pdf_split_every_n_execute,
        utilities_service::utilities_hash_text,
        utilities_service::utilities_hash_algorithms,
        utilities_service::utilities_checksum,
        utilities_service::utilities_base64_encode,
        utilities_service::utilities_base64_decode,
        utilities_service::utilities_uuid_generate,
        utilities_service::utilities_uuid_validate,
        utilities_service::utilities_timestamp_convert,
        utilities_service::utilities_timestamp_now,
        utilities_service::utilities_url_encode,
        utilities_service::utilities_url_decode,
        utilities_service::utilities_url_parse,
        utilities_service::utilities_regex_find,
        utilities_service::utilities_regex_replace,
        utilities_service::utilities_regex_capabilities,
        utilities_service::utilities_color_convert,
        utilities_service::utilities_color_contrast,
        utilities_service::utilities_checksum_file,
        utilities_service::utilities_export_report,
    ])
}

/// 导出 IPC 绑定到 `ui/src/generated/bindings.ts`。
/// 由 `npm run generate:bindings`（集成测试 `export_bindings`）触发；
/// 开发构建启动时也会自动刷新。
pub fn export_bindings() {
    ipc_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("// Generated by tauri-specta. DO NOT EDIT — regenerate with `npm run generate:bindings`.\n"),
            "../ui/src/generated/bindings.ts",
        )
        .expect("failed to export IPC bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = ipc_builder();

    // 仅在开发构建时导出绑定；CI / 发布构建使用仓库中已提交的生成文件。
    #[cfg(debug_assertions)]
    export_bindings();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let log_guard = logging::init(app.handle())?;
            app.manage(state::AppState::new(
                log_guard,
                tools::build_file_tools_registry(),
            ));
            tracing::info!("Weave started (M1 File Core)");
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|_app, event| {
            if let tauri::RunEvent::Exit = event {
                tracing::info!("Weave exited");
            }
        })
}
