//! Weave 桌面壳（Tauri 2 + React + TypeScript + Vite）。
//!
//! 依赖方向：UI → IPC → Application(本 crate) → weave-core → Adapter → OS。
//! 本 crate 是 IPC 边界与 Application 层，不承载领域逻辑。
//! 单元测试放在 `tests/`（集成测试目标）——测试可执行文件需要嵌入
//! common-controls manifest 才能在 Windows 上启动（见 build.rs）。

pub mod app_info;
pub mod commands;
pub mod config;
pub mod files_dto;
pub mod jobs;
pub mod logging;
pub mod state;
pub mod tools;

use tauri::Manager;
use tauri_specta::{Builder, collect_commands};

/// IPC 契约：所有命令集中注册，类型由 tauri-specta 生成到 `ui/src/generated/bindings.ts`。
pub fn ipc_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::ping,
        commands::get_app_info,
        commands::inspect_path,
        commands::get_app_config,
        commands::set_app_config,
        commands::inspect_file,
        commands::hash_file,
        commands::analyze_directory,
        commands::get_job,
        commands::cancel_job,
        commands::list_tools,
    ])
}

/// 导出 IPC 绑定到 `ui/src/generated/bindings.ts`。
/// 由 `npm run generate:bindings`（集成测试 `export_bindings`）触发；
/// 开发构建启动时也会自动刷新。
pub fn export_bindings() {
    ipc_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("// Generated by tauri-specta. DO NOT EDIT — regenerate with `npm run generate:bindings`.\n"),
            "../ui/src/generated/bindings.ts",
        )
        .expect("failed to export IPC bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = ipc_builder();

    // 仅在开发构建时导出绑定；CI / 发布构建使用仓库中已提交的生成文件。
    #[cfg(debug_assertions)]
    export_bindings();

    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let log_guard = logging::init(app.handle())?;
            app.manage(state::AppState::new(
                log_guard,
                tools::build_file_tools_registry(),
            ));
            tracing::info!("Weave started (M0 Foundation)");
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|_app, event| {
            if let tauri::RunEvent::Exit = event {
                tracing::info!("Weave exited");
            }
        })
}
